[2024-07-24T07:39:49.946+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T07:39:49.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyTest.send_email manual__2024-07-24T07:39:44.372743+00:00 [queued]>
[2024-07-24T07:39:49.973+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyTest.send_email manual__2024-07-24T07:39:44.372743+00:00 [queued]>
[2024-07-24T07:39:49.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T07:39:49.987+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_email> on 2024-07-24 07:39:44.372743+00:00
[2024-07-24T07:39:49.994+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4395) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T07:39:49.996+0000] {standard_task_runner.py:64} INFO - Started process 4398 to run task
[2024-07-24T07:39:49.996+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'MyTest', 'send_email', 'manual__2024-07-24T07:39:44.372743+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/MyTest.py', '--cfg-path', '/tmp/tmplffs2m3s']
[2024-07-24T07:39:49.997+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask send_email
[2024-07-24T07:39:50.036+0000] {task_command.py:426} INFO - Running <TaskInstance: MyTest.send_email manual__2024-07-24T07:39:44.372743+00:00 [running]> on host ed4de24231fa
[2024-07-24T07:39:50.175+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MyTest' AIRFLOW_CTX_DAG_ID='MyTest' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T07:39:44.372743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T07:39:44.372743+00:00'
[2024-07-24T07:39:50.176+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T07:39:50.196+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T07:39:50.197+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MyTest.py", line 143, in send_email_func
    body += df.to_html(index=False, encoding='utf-8')  # Ensure correct encoding
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3235, in to_html
    return fmt.DataFrameRenderer(formatter).to_html(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1075, in to_html
    return save_to_buffer(string, buf=buf, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1171, in save_to_buffer
    with get_buffer(buf, encoding=encoding) as f:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1195, in get_buffer
    raise ValueError("buf is not a file name and encoding is specified.")
ValueError: buf is not a file name and encoding is specified.
[2024-07-24T07:39:50.211+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=MyTest, task_id=send_email, run_id=manual__2024-07-24T07:39:44.372743+00:00, execution_date=20240724T073944, start_date=20240724T073949, end_date=20240724T073950
[2024-07-24T07:39:50.223+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task send_email (buf is not a file name and encoding is specified.; 4398)
[2024-07-24T07:39:50.250+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T07:39:50.264+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T07:39:50.266+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
