[2024-07-18T06:13:07.531+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T06:13:07.596+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oper_Auto_O.send_email manual__2024-07-18T06:13:02.260990+00:00 [queued]>
[2024-07-18T06:13:07.615+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oper_Auto_O.send_email manual__2024-07-18T06:13:02.260990+00:00 [queued]>
[2024-07-18T06:13:07.616+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-07-18T06:13:07.650+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_email> on 2024-07-18 06:13:02.260990+00:00
[2024-07-18T06:13:07.662+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5019) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-18T06:13:07.665+0000] {standard_task_runner.py:63} INFO - Started process 5031 to run task
[2024-07-18T06:13:07.675+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Oper_Auto_O', 'send_email', 'manual__2024-07-18T06:13:02.260990+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/Prince.py', '--cfg-path', '/tmp/tmpzskrrwse']
[2024-07-18T06:13:07.682+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask send_email
[2024-07-18T06:13:07.802+0000] {task_command.py:426} INFO - Running <TaskInstance: Oper_Auto_O.send_email manual__2024-07-18T06:13:02.260990+00:00 [running]> on host a0a98051551f
[2024-07-18T06:13:07.935+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='tanakitsiriteerapan@gmail.com' AIRFLOW_CTX_DAG_OWNER='Diw' AIRFLOW_CTX_DAG_ID='Oper_Auto_O' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T06:13:02.260990+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T06:13:02.260990+00:00'
[2024-07-18T06:13:07.937+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T06:13:07.955+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T06:13:07.956+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Prince.py", line 49, in send_email
    df = query_data_from_oracle()
         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'PythonOperator' object is not callable
[2024-07-18T06:13:07.968+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=Oper_Auto_O, task_id=send_email, execution_date=20240718T061302, start_date=20240718T061307, end_date=20240718T061307
[2024-07-18T06:13:07.985+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 91 for task send_email ('PythonOperator' object is not callable; 5031)
[2024-07-18T06:13:08.003+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-18T06:13:08.025+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T06:13:08.028+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
